Array using Numpy


In [255]:
import numpy as np

In [256]:
arr = np.array([1,2,3,4])

In [257]:
print(arr)  # Output the array to verify

[1 2 3 4]


In [258]:
a = [1,2,3.5,"Hllo",4]

In [259]:
a

[1, 2, 3.5, 'Hllo', 4]

In [260]:
np.array(a)

array(['1', '2', '3.5', 'Hllo', '4'], dtype='<U32')

In [261]:
l = [[1,3,5], [2,4,6]]  # Example of a 2D array with specific indices

In [262]:
l

[[1, 3, 5], [2, 4, 6]]

In [263]:
np.array(l)

array([[1, 3, 5],
       [2, 4, 6]])

Array Generation Function


In [264]:
arr = np.arange(1,11)

In [265]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [266]:
arr = np.zeros((6, 6))  # Create a 3x4 array filled with zeros

In [267]:
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [268]:
arr = np.ones((3, 4))  # Create a 3x4 array filled with ones

In [269]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [270]:
arr = np.linspace(1, 5, 5)  # Create an array with 5 evenly spaced values between 1 and 10
arr

array([1., 2., 3., 4., 5.])

Random Number generation

In [271]:
import random

In [272]:
np.random.rand(5) # Generate 5 random numbers between 0 and 1

array([0.09066592, 0.89530245, 0.90501907, 0.18749959, 0.25736066])

In [273]:
np.random.randn(5)  # Generate 5 random numbers from a standard normal distribution"

array([-0.15053358,  1.71205023,  0.05459288,  0.49071744,  1.02135662])

In [274]:
np.random.randint(10,20,10) # Generate a random integer between 0 and 5

array([12, 12, 14, 10, 14, 11, 11, 10, 17, 16])

Array Attributes

In [275]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [276]:
arr.shape

(3, 3)

In [277]:
arr.size

9

In [278]:
arr.dtype

dtype('int64')

Array Methods

In [279]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [280]:
arr.min()

1

In [281]:
arr.max()

9

In [282]:
arr.sum()  # Sum of all elements in the array

45

In [283]:
arr.argmax()  # Index of the maximum element in the array

8

In [284]:
arr.argmin()  # Index of the minimum element in the array

0

Reshaping and Resizing

In [285]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [286]:
arr = arr.reshape(6,5)  # Reshape the array to 6 rows and 5 columns
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

Numpy indexing and Slicing of Vectors

In [287]:
arr = np.arange(11,21) # Create a new array with values from 11 to 20
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [288]:
arr[6]

17

In [289]:
arr[3:8]

array([14, 15, 16, 17, 18])

In [290]:
arr[0:5]

array([11, 12, 13, 14, 15])

In [291]:
arr[3:]

array([14, 15, 16, 17, 18, 19, 20])

In [292]:
arr[3:10]

array([14, 15, 16, 17, 18, 19, 20])

In [293]:
arr[3::2]

array([14, 16, 18, 20])

Numpy Indexing and Slicing of Matrix
"

In [294]:
arr = np.arange(1,31).reshape(6,5)  # Create a 6x5 array with values from 1 to 30
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [295]:
arr[0] # Access the first element of the array

array([1, 2, 3, 4, 5])

In [296]:
arr[1] # Access the second element of the array

array([ 6,  7,  8,  9, 10])

In [297]:
arr[5]  # Access the sixth element of the array

array([26, 27, 28, 29, 30])

In [298]:
arr[0,0]

1

In [299]:
arr[0,4]

5

In [300]:
arr[5,4]

30

In [301]:
arr[0:2, 1:3]

array([[2, 3],
       [7, 8]])

In [302]:
arr[3:7, 3:5]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [303]:
arr[:, 2]

array([ 3,  8, 13, 18, 23, 28])

Bollean Indexing

In [304]:
arr = np.arange(11,21)  # Create a new array with values from 11 to 20
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [305]:
bool_index = arr % 2 == 0  # Create a boolean index for even numbers
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [306]:
arr = arr[bool_index]  # Use the boolean index to filter the array
arr

array([12, 14, 16, 18, 20])

Array Operations

In [307]:
import numpy as np

1. Arithmetic Operations
2. Broadcasting
3. Deep and Shallow COpy
4. Matrix operation
5. Advance Array Manipulation
6. Stacking Array
7. Splitting Array


In [308]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
a2

array([ 6,  7,  8,  9, 10])

In [309]:
arr2 = a1 + a2
arr2  # Element-wise addition of two arrays

array([ 7,  9, 11, 13, 15])

In [310]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [311]:
a1 / a2  # Element-wise division of two arrays

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [312]:
a1 // a2  # Element-wise floor division of two arrays

array([0, 0, 0, 0, 0])

In [313]:
a1 ** a2  # Element-wise exponentiation of two arrays

array([      1,     128,    6561,  262144, 9765625])

Broadcasting

In [314]:
l = [10,20,30,40,50]
arr = np.array(l)

In [315]:
arr + 10

array([20, 30, 40, 50, 60])

In [316]:
m =  np.arange(1,26).reshape(5,5)

In [317]:
m

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [318]:
m + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

Deep and Shallow Copy


In [319]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [320]:
slice = a[:5]
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [321]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [322]:
a[4:6] * 10

array([50, 60])

In [323]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [324]:
b = a.copy() # Create a new variable b that points to the same array as a

In [325]:
b[0] = 12  # Modify the first element of the array b

In [326]:
b

array([12,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [327]:
a # The original array is modified

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Matrix operations

In [328]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [329]:
A

array([[1, 2],
       [3, 4]])

In [330]:
B

array([[5, 6],
       [7, 8]])

In [331]:
A * B

array([[ 5, 12],
       [21, 32]])

Multiplication of MAtrix
[1X5 + 2X7, 1X6 + 2X8]
[3X5 + 4X7, 3X6 + 4X8]

In [332]:
A @ B

array([[19, 22],
       [43, 50]])

Transpose of Matrix -> Row become column and column become row

In [333]:
A.T

array([[1, 3],
       [2, 4]])

Advance Array Manipulation

Stacking Array -> Jst add two arrays

You cannot Stack two Matrix, only two arrays or vectors

In [334]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [335]:
#Vertical Stack

np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [336]:
#Horizontal Stack

np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [337]:
#Column Stack

np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

Splitting Array

In [338]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [339]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [340]:
a = np.vsplit(c,4)

In [341]:
for i in a :
    print(i)  # Print each element in the array a

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]


Exercises


Valid Sudoku

In [342]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [343]:
b = np.sum(s,axis=1)
for i in b:
    if i != 45:
        print("Not a valid Sudoku")
        break
else:
    print("Valid Sudoku")

Valid Sudoku


In [344]:
c = np.sum(s,axis=0)
for i in c:
    if i != 45:
        print("Not a valid Sudoku")
        break
else:
    print("Valid Sudoku")

Valid Sudoku


In [345]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n = s[i:i+3, j:j+3]  # Print each 3x3 sub-grid of the Sudoku puzzle
        print(n.sum())

45
45
45
45
45
45
45
45
45


General Questions

In [346]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [347]:
#Get the shape of the matrix.
data.shape

(5, 3)

In [348]:
#Find the average age of students.
np.mean(data[:, 0])  # Average age of students

18.4

In [349]:
#Extract Math marks of all students.
data[:, 1]  # Math marks of all students

array([85, 92, 76, 65, 90])

In [350]:
#Find the highest Science mark.
np.max(data[:, 2])  # Highest Science mark

95

In [351]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [352]:
#Get details of the student who scored more than 90 in Math.
data[data[:,1] > 90]

array([[19, 92, 88]])

In [353]:
#Increase Math marks of all students by 5.
data[:, 1] += 5 # Increase Math marks by 5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [354]:
#Find how many students are younger than 19.
len(data[data[:, 0] < 19])

3

In [355]:
#Calculate the average marks in each subject (column-wise mean).
mean2 = np.mean(data[:, 1:], axis=0)  # Calculate mean for each subject (Math and Science)
mean2

array([86.6, 83.2])

In [356]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1]>=80) & (data[:,2]>=80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [357]:
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [359]:
#Replace all Science marks < 75 with 0.
data[:,2][data[:,2] <75] = 0

In [360]:
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])